import { createReadStream } from 'fs';
import csv from 'csv-parser';
import { Contact } from '@prisma/client';
import { CampaignRepository, CreateContactInput } from '../db/repositories/campaignRepository';
import { logger } from '../utils/logger';

export class ContactService {
  private campaignRepository: CampaignRepository;

  constructor() {
    this.campaignRepository = new CampaignRepository();
  }

  async parseCSVFile(filePath: string): Promise<Contact[]> {
    return new Promise((resolve, reject) => {
      const contacts: Contact[] = [];

      createReadStream(filePath)
        .pipe(csv())
        .on('data', (row) => {
          try {
            const contact = this.validateContact(row);
            if (contact) {
              contacts.push(contact);
            }
          } catch (error) {
            logger.warn(`Invalid contact row: ${JSON.stringify(row)}`, error);
          }
        })
        .on('end', () => {
          resolve(contacts);
        })
        .on('error', (error) => {
          reject(error);
        });
    });
  }

  private validateContact(row: any): Contact | null {
    // Extract phone number - try different field names
    let phone = row.phone || row.phone_number || row.mobile || row.contact || row.number;
    
    if (!phone) {
      logger.warn('Contact missing phone number', { row });
      return null;
    }

    // Clean phone number
    phone = this.cleanPhoneNumber(phone);
    
    if (!phone) {
      logger.warn('Invalid phone number format', { originalPhone: row.phone || row.phone_number });
      return null;
    }

    // Check against do-not-call list (basic implementation)
    const isDoNotCall = this.isDoNotCallNumber(phone);

    return {
      id: '', // Will be generated by database
      campaignId: null, // Will be set when associated with campaign
      phone,
      name: row.name || row.full_name || row.first_name || null,
      email: row.email || null,
      isValid: !isDoNotCall,
      isDoNotCall,
      validationError: isDoNotCall ? 'Number is on do-not-call list' : null,
      createdAt: new Date(),
      updatedAt: new Date(),
    };
  }

  private cleanPhoneNumber(phone: string): string | null {
    // Remove all non-digit characters
    const cleaned = phone.replace(/\D/g, '');
    
    // Basic validation - should be 10-15 digits
    if (cleaned.length < 10 || cleaned.length > 15) {
      return null;
    }
    
    return cleaned;
  }

  private isDoNotCallNumber(phone: string): boolean {
    // Basic do-not-call list implementation
    // In production, this would be a database lookup or API call
    const doNotCallNumbers = [
      '1234567890', // Example do-not-call number
      '5555555555', // Example do-not-call number
    ];
    
    return doNotCallNumbers.includes(phone);
  }

  async uploadContactsFromCSV(campaignId: string, filePath: string): Promise<Contact[]> {
    const contacts = await this.parseCSVFile(filePath);
    
    // Associate contacts with campaign and convert to CreateContactInput format
    const contactsWithCampaign: CreateContactInput[] = contacts.map(contact => ({
      campaignId,
      phone: contact.phone,
      name: contact.name || undefined,
      email: contact.email || undefined,
      isValid: contact.isValid,
      isDoNotCall: contact.isDoNotCall,
      validationError: contact.validationError || undefined,
    }));
    
    // Save to database
    return this.campaignRepository.createContacts(contactsWithCampaign);
  }

  async validatePhoneNumbers(phones: string[]): Promise<Contact[]> {
    return phones.map(phone => {
      const cleanedPhone = this.cleanPhoneNumber(phone);
      
      if (!cleanedPhone) {
        return {
          id: '',
          campaignId: null,
          phone,
          name: null,
          email: null,
          isValid: false,
          isDoNotCall: false,
          validationError: 'Invalid phone number format',
          createdAt: new Date(),
          updatedAt: new Date(),
        };
      }

      const isDoNotCall = this.isDoNotCallNumber(cleanedPhone);

      return {
        id: '',
        campaignId: null,
        phone: cleanedPhone,
        name: null,
        email: null,
        isValid: !isDoNotCall,
        isDoNotCall,
        validationError: isDoNotCall ? 'Number is on do-not-call list' : null,
        createdAt: new Date(),
        updatedAt: new Date(),
      };
    });
  }
}